name: Terraform Destroy Workspace

inputs:
  terraform_version:
    type: number
    default: '1.3.7'
    description: Terraform Version to install on runner
  terraform_workspace_name:
    type: string
    description: Name for Teraform Workspace e.g dev01 or uat01

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v3
  - uses: hashicorp/setup-terraform@v2
    with:
      terraform_version:  ${{ inputs.terraform_version }}

  - name: destroy all terraform workspace 
    if: ${{ inputs.terraform_workspace_name == null }} 
    run: |
      terraform workspace select "${{ github.actor }}" 
      terraform workspace list | grep -v default | xargs -n 1 terraform workspace select 
      terraform workspace list | grep -v default | xargs -n 1 terraform workspace delete 
    shell: bash
