name: deploy

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: CloudwithNicholas/github-workflows/.github/workflows/github_linter.yml@main 
    with:
      username: CloudwithNicholas
    secrets:
      token: ${{ secrets.TOKEN }}

  # call-workflow-B:
  #   uses: CloudwithNicholas/github-workflows/.github/workflows/terraform-plan.yml@main 
  #   with:
  #     username: CloudwithNicholas
  #   secrets:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     TF_ACTION_WORKING_DIR: 'terraform'
  jobs:
    call-repo:
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GHA_WORKFLOW_TRIGGER }}
        script: |
          const result = await github.rest.actions.createWorkflowDispatch({
            owner: 'CloudwithNicholas',
            repo: 'backend-repo',
            workflow_id: 'deploy.yml',
            ref: 'heads/main'
          })
          console.log(result)
