name: "deploy_dev"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
      tf_version:
        description: 'Terraform version'
        required: true
        default: 'latest'
      tf_vars_file:
        description: 'Terraform variables file'
        required: true
        default: 'terraform.tfvars'
      tf_key:
        description: 'Terraform state key'
        required: true
        default: 'terraform-dev'
      tfbucketname:
        description: 'Terraform state bucket name'
        required: true
        default: 'tfstate-nick1'
      tf_environment:
        description: 'Terraform environment'
        required: true
        default: 'dev'
      path:
        description: 'Terraform path'
        required: true
        default: 'terraform'
      tf_action:
        description: 'Terraform action'
        required: true
        default: 'plan'

jobs:  
  Plan_Dev:
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform-plan.yml@main
    with:
      path: terraform             
      tf_version: latest
      tfbucketname : tfstate-nick1       
      tf_key: terraform-dev          
      tf_vars_file: terraform.tfvars
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     

  DeployDev:
    needs: Plan_Dev
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform_apply.yml@main
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick1              
      tf_key: terraform-dev            
      tf_vars_file: terraform.tfvars
      tf_environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     

  int_plan:
    needs: DeployDev
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform-plan.yml@main
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick              
      tf_key: terraform-dev            
      tf_vars_file: terraform.tfvars
      tf_environment: int
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     

  int_deploy:
    needs: DeployDev
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform_apply.yml@main 
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick              
      tf_key: terraform-dev            
      tf_vars_file: terraform.tfvars
      tf_environment: int
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     

  pre-pod_plan:
    needs: DeployDev
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform-plan.yml@main
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick              
      tf_key: terraform-dev            
      tf_vars_file: terraform.tfvars
      tf_environment: pre-pod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     

  pre-pod_deploy:
    needs: DeployDev
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform_apply.yml@main 
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick              
      tf_key: terraform-dev            
      tf_vars_file: terraform.tfvars
      tf_environment: pre-pod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

  prod_plan:
    needs: DeployDev
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform-plan.yml@main
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick              
      tf_key: terraform-dev            
      tf_vars_file: terraform.tfvars
      tf_environment: pre-pod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

  deploy_deploy:
    needs: DeployDev
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform_apply.yml@main 
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick              
      tf_key: terraform-dev            
      tf_vars_file: terraform.tfvars
      tf_environment: pre-pod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
