name: deploy

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: CloudwithNicholas/github-workflows/.github/workflows/github_linter.yml@main 
    with:
      username: CloudwithNicholas
    secrets:
      token: ${{ secrets.TOKEN }}

  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'CloudwithNicholas',
              repo: 'backend-repo',
              workflow_id: 'deploy.yml',
              ref: 'heads/main'
            })
            console.log(result)