name: "deploy_dev"

on:
  workflow_dispatch:
    inputs: 
      dev_deploy:
        description: Enable deployment to development environment
        required: true
        default: true
        type: boolean
      int_deploy:
        description: Enable deployment to integration environment
        required: true
        default: false
        type: boolean
      preprod_deploy:
        description: Enable deployment to preproduction environment
        required: false
        default: false
        type: boolean
      prod_deploy:
        description: Enable deployment to production environment
        required: false
        default: false
        type: boolean
      

jobs:

  Plan_Dev:
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform-plan.yml@main
    if: ${{ inputs.dev_deploy }}
    with:
      path: terraform             
      tf_version: latest
      tfbucketname : tfstate-nick1       
      tf_key: terraform-dev          
      tf_vars_file: ../etc/terraform.tfvars
      environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     

  DeployDev:
    needs: Plan_Dev
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform-apply.yml@main
    if: ${{ inputs.dev_deploy }}
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick1             
      tf_key: terraform-dev            
      tf_vars_file: ../etc/terraform.tfvars
      environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  int_plan:
    needs: DeployDev
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform-plan.yml@main
    if: ${{ inputs.int_deploy }}
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick1           
      tf_key: terraform-int           
      tf_vars_file: ../etc/terraform.tfvars
      terraform_workspace_name: 
      environment: int_deploy
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     

  int_deploy:
    needs: int_plan
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform-apply.yml@main
    if: ${{ inputs.int_deploy }}
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick1          
      tf_key: terraform-int            
      tf_vars_file: ../etc/terraform.tfvars
      environment: int_deploy
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

  pre-pod_plan:
    needs: int_deploy 
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform-plan.yml@main
    if: ${{ inputs.preprod_deploy }}
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick1              
      tf_key: terraform-preprod         
      tf_vars_file: ../etc/terraform.tfvars
      environment: preprod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     

  pre-pod_deploy:
    needs: pre-pod_plan
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform-apply.yml@main
    if: ${{ inputs.preprod_deploy }}
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick1            
      tf_key: terraform-preprod           
      tf_vars_file: ../etc/terraform.tfvars
      environment: preprod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

  prod_plan:
    needs: pre-pod_deploy
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform-plan.yml@main
    if: ${{ inputs.prod_deploy }}
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick1              
      tf_key: terraform-prod           
      tf_vars_file: ../etc/terraform.tfvars
      environment: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

  prod_deploy:
    needs: prod_plan
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform-apply.yml@main
    if: ${{ inputs.prod_deploy }}
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick1              
      tf_key: terraform-prod            
      tf_vars_file: ../etc/terraform.tfvars
      environment: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
