name: deploy

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: CloudwithNicholas/github-workflows/.github/workflows/github_linter.yml@reuseable-workflow 
    with:
      username: CloudwithNicholas
    secrets:
      token: ${{ secrets.TOKEN }}

  call-workflow-B:
    uses: CloudwithNicholas/github-workflows/.github/workflows/github_linter.yml@reuseable-workflow 
    with:
      username: CloudwithNicholas
    secrets:
      token: ${{ secrets.TOKEN }}

