name: "Workspce Deploy"

on:
  workflow_dispatch:
    inputs:
      env_account:
        required: true
        type: string      
      environment:
        required: true
        type: string     
      terraform_workspace_name:
        required: false
        type: string    

permissions:
  id-token: write
  contents: read

env: 
  terraform_actions_working_dir: ${{ github.workspace }}/components/

jobs:
  env-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
         
      - name: TF workspace
        uses: NickAzureDevops/github-workflows/.github/actions/terraform-workspace@invoke-pipeline-across-repositories
        with:
          terraform_workspace_name: ${{ inputs.terraform_workspace_name }}
          terraform_version: 1.3.7

      - name: Create Workspace tfvars
        run: |
          cp ./etc/terraform.tfvars ./etc/${{ env.WORKSPACE }}.tfvars   
        
