name: "deploy_dev"
on:
  workflow_dispatch:
    
jobs:
  aws_authentication:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.otp.outputs.test }}
    steps:
      - uses: actions/checkout@v3
      - uses: step-security/wait-for-secrets@v1
        id: otp
        with:
          secrets: |
            AWS_Authencation: 
              name: 'Authenticate to AWS from 2FA'
              description: 'Authenicating to AWS, please wait'
      - run: |
          echo ${{ steps.get-otp.outputs.AWS_Authencation }}  >> $GITHUB_OUTPUT

  job2:
      runs-on: ubuntu-latest
      needs: aws_authentication
      steps:
        - run: echo ${{ needs.job1.outputs.aws_authentication }}

  Plan_Dev:
    needs: aws_authentication
    uses: CloudwithNicholas/github-workflows/.github/workflows/terraform-plan.yml@invoke-pipeline-across-repositories
    with:
      path: terraform             
      tf_version: latest
      tfbucketname : tfstate-nick       
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   

  DeployDev:
    needs: Plan_Dev
    uses: CloudwithNicholas/github-workflows/.github/workflows/terraform_apply.yml@invoke-pipeline-across-repositories
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick              
      tf_environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     
