name: "Workspace Deploy"

on:
  push:
    branches:
      - invoke-pipeline-across-repositories
  workflow_dispatch:
    inputs:     
      terraform_workspace_name:
        required: false
        type: string  
      terraform_workspace_destroy:
        required: false
        type: boolean
      quick_deploy:
        description: Run quick deploy.
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

env: 
  terraform_actions_working_dir: ${{ github.workspace }}/terraform/

jobs:
  create_workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
       

  Plan_Dev:
    needs: create_workspace
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform-plan.yml@main
    if: contains(inputs.quick_deploy, 'true') 
    with:
      path: terraform    
      terraform_workspace_name: ${{ inputs.terraform_workspace_name }}
      tf_version: latest
      tfbucketname : tfstate-nick1       
      tf_key: terraform-dev          
      tf_vars_file: ../dev/terraform.tfvars
      quick_deploy: "--var-file=../var/terraform.tfvars"
      environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     
      
  DeployDev:
    needs: Plan_Dev
    uses: NickAzureDevops/github-workflows/.github/workflows/terraform_apply.yml@main
    if: contains(inputs.quick_deploy, 'true') 
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick1              
      tf_key: terraform-dev            
      tf_vars_file: ../dev/terraform.tfvars
      environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     

