name: "deploy_dev"
on:
  workflow_dispatch:

env:
  SOME_VAR: test

jobs:
  aws_authenication:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      some_var: ${{ steps.step1.outputs.some_var }}
    steps:
      - uses: actions/checkout@v3
      - uses: step-security/wait-for-secrets@v1
        id: get-otp
        with:
          secrets: |
            authenication: 
              name: 'Dummy secret'
              description: 'Dummy secret to demo wait-for-secrets' 
      - run: |
          echo ${{ steps.get-otp.outputs.authenication }}

  job1:
    uses: CloudwithNicholas/github-workflows/.github/workflows/reuseable-output.yml@invoke-pipeline-across-repositories

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
  
  Plan_Dev:
    needs: aws_authenication
    uses: CloudwithNicholas/github-workflows/.github/workflows/terraform-plan.yml@invoke-pipeline-across-repositories
    with:
      path: terraform             
      tf_version: latest
      tfbucketname : tfstate-nick       
      tf_key: terraform-dev          
      tf_vars_file: terraform.tfvars
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     

  DeployDev:
    needs: Plan_Dev
    uses: CloudwithNicholas/github-workflows/.github/workflows/terraform_apply.yml@invoke-pipeline-across-repositories
    with:
      path: terraform             
      tf_version: latest 
      tfbucketname : tfstate-nick              
      tf_key: terraform-dev            
      tf_vars_file: terraform.tfvars
      tf_environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}            
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     

# jobs:
#   call-workflow-A:
#     uses: CloudwithNicholas/github-workflows/.github/workflows/github_linter.yml@main 
#     with:
#       username: CloudwithNicholas
#     secrets:
#       token: ${{ secrets.TOKEN }}
