name: "destroy_dev"
on:
  workflow_dispatch:

jobs:
  build-plan:
    runs-on: ubuntu-latest    
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Setup Terraform                                                                      
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          id: init
          run: terraform init -backend-config="bucket=${{ env.tfbucketname }}" --backend-config="key=$TF_KEY"
          
        - name: Terraform Plan
          id: plan
          run: terraform plan --var-file=$TF_VARS --out=plan.tfplan >> $GITHUB_OUTPUT
          continue-on-error: true

        - name: Terraform destroy
          id: destroy
          run: terraform destroy plan.tfplan