name: "Environment Deploy"

on:
  push:
    branches:
    - main
#   schedule:
     # Runs "At 20:00 on every day-of-week from Monday through Friday"
    # - cron: '0 20 * * 1-5'   
  workflow_dispatch:
    inputs:
        group:
          description: 'Environment Group'
          required: true
          default: 'dev'
        terraform_workspace_name:
          description: 'Terraform Workspace Name'
          required: true
          default: 'dev'

permissions:
  id-token: write
  contents: read

env: 
  terraform_actions_working_dir: ${{ github.workspace }}/components/

jobs:
  quick_deploy_destroy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.group }}
    steps:
      - uses: actions/checkout@v3
        
      # - name: AWS Authentication
      #   uses: dvsa/.github/.github/actions/aws-auth@main
      #   with:
      #     aws_role: dvsamot-recalls-infra-github
      #     aws_region: eu-west-1
      #     aws_account_id: 769086804114

      - name: Destroy All Terraform Workspace 
        run: |
            terraform workspace list * 
            | grep -v default | xargs -I {} terraform workspace select {} && terraform destroy -auto-approve 
        shell: bash
