name: "destroy_dev"
on:
  workflow_dispatch:

env: 
  TF_KEY: terraform-dev 
  tfbucketname: tfstate-nick1 
  tf_version: latest
  TF_VARS: terraform.tfvars

jobs:
  detroy_dev:
    runs-on: ubuntu-latest    
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2.0.3
          with:
            terraform_version: ${{ env.TF_VERSION }}

        - name: Terraform Init
          id: init
          run: terraform init -backend-config="bucket=${{ env.tfbucketname }}" --backend-config="key=${{ env.TF_KEY }}"
          
        - name: Terraform Plan
          id: plan
          run: terraform plan --var-file=$TF_VARS --out=plan.tfplan
          continue-on-error: true

        - name: Terraform destroy
          id: destroy
          run: terraform destroy plan.tfplan