name: "destroy_dev"
on:
  workflow_dispatch:

jobs:
  destroy_dev:
    runs-on: ubuntu-latest
    env: 
      tf_key: terraform-dev     
      tfbucketname: tfstate-nick1 
      tf_version: latest
      TF_VARS: terraform.tfvars
      environment: dev
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: terraform

    steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2.0.3
          with:
            terraform_version: ${{ env.TF_VERSION }}

        - name: Terraform Init
          id: init
          run: terraform init -backend-config="bucket=${{ env.tfbucketname }}" --backend-config="key=${{ env.tf_key }}"
          
        - name: Terraform Plan
          id: plan
          run: terraform plan 
          continue-on-error: true

        - name: Terraform destroy
          id: destroy
          run: terraform destroy plan.tfplan