name: "deploy_dev"
on:
  workflow_dispatch:
    
jobs:
  build-plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.tf_environment }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.path }} 
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Setup Terraform                                                                      
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          id: init
          run: terraform init -backend-config="bucket=${{ env.tfbucketname }}"
          
        - name: Terraform Plan
          id: plan
          run: terraform plan --var-file=$TF_VARS --out=plan.tfplan >> $GITHUB_OUTPUT
          continue-on-error: true

        - name: Terraform destroy
          id: destroy
          run: terraform destroy -auto-approve