name: "Destroy workspace"

on:
#   schedule:
     # Runs "At 20:00 on every day-of-week from Monday through Friday"
    # - cron: '0 20 * * 1-5'   
  workflow_dispatch:
    inputs:
      group:
        description: 'Environment Group'
        required: true
        default: 'dev'
      terraform_workspace_name:
        description: 'Terraform Workspace Name'
        required: false
        default: 'dev'

permissions:
  id-token: write
  contents: read

env: 
  terraform_actions_working_dir: ${{ github.workspace }}/terraform/

jobs:
  quick_deploy_destroy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.group }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Destroy TF Workspace
        uses: NickAzureDevops/github-workflows/.github/actions/terraform-workspace-destroy@main
        with:
          terraform_workspace_name: ${{ inputs.terraform_workspace_name }}
          terraform_version: 1.3.7
