name: "workspace destroy"

on:
  push:
    branches:
    - main
#   schedule:
     # Runs "At 20:00 on every day-of-week from Monday through Friday"
    # - cron: '0 20 * * 1-5'   
  workflow_dispatch:
    inputs:
      terraform_workspace_name:
        description: 'Terraform Workspace Name'
        required: true

permissions:
  id-token: write
  contents: read

env: 
  terraform_actions_working_dir: ${{ github.workspace }}/terraform/

jobs:
  quick_deploy_destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Destroy All Terraform Workspace 
        if: ${{ inputs.terraform_workspace_name == 'destroy' }} 
        run: |
            terraform workspace list | grep -v default | xargs -I {} terraform workspace select {} && terraform destroy -auto-approve 
        shell: bash
