name: Reusable output

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "::set-output name=firstword::hello"
      - id: step2
        run: echo "::set-output name=secondword::world"


  # aws_authenication:
  #   name: Generate output
  #   permissions:
  #     id-token: write
  #   runs-on: ubuntu-latest
  #   outputs:
  #     output1: ${{ steps.get-otp.outputs.firstword }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: step-security/wait-for-secrets@v1
  #       id: get-otp
  #       with:
  #         secrets: |
  #           authenication: 
  #             name: '2FA secret'
  #             description: 'Please Enter your 2FA Token' 
  #     - run: |
  #         echo ${{ steps.get-otp.outputs.authenication }} >> $GITHUB_OUTPUT
  #         echo 

