name: terraform_plan

on:
  workflow_call:
    inputs:
      GITHUB_TOKEN:
      TF_ACTION_WORKING_DIR:
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  terraform_plan:
    name: terraform_plan
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: 'Terraform Format'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_working_dir: "./terraform"
        tf_actions_subcommand: 'fmt'
        tf_actions_version: ${{ env.tf_actions_version }}
      
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        tf_actions_working_dir: "./terraform"
        tf_actions_subcommand: 'init'
        tf_actions_version: ${{ env.tf_actions_version }}
      
    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        tf_actions_working_dir: "./terraform"
        tf_actions_subcommand: 'plan'
        tf_actions_version: ${{ env.tf_actions_version }}
      
  