name: terraform_apply

on:
  workflow_call:
    inputs:
     path:
      description: 'Specifies the path of the root terraform module.'
      required: true
      type: string
    tf_version:
      description: 'Specifies version of Terraform to use. e.g: 1.1.0 Default=latest.'
      required: false
      type: string
      default: latest
    tf_environment:
      description: 'Specifies the GitHub deployment environment.'
      required: false
      type: string
      default: null
    tf_vars_file:
      description: 'Specifies the Terraform TFVARS file.'
      required: true
      type: string
    secrets:
      GITHUB_TOKEN:
        description: '"GitHub token.'
        required: true
      AWS_ACCESS_KEY_ID:
        description: '"AWS Access Key ID.'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key.'
        required: true
        
jobs:
   tf_apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.tf_environment }}
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
   env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      tfbucketstate: tfstate-nick

   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
 
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0
    
     - name: Terraform init
       id: init
       run: terraform init -backend-config="bucket=${{ env.tfbucketstate }}"

     - name: Terraform apply
       id: apply
       run: terraform apply -auto-approve -input=false