name: terrform_apply

on:
  push:
    branches:
      - master

jobs:
  tf_fmt:
    name: terrform_apply
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

      

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
      env:
        tf_actions_working_dir: "./terraform"
        tf_actions_subcommand: 'apply'
        tf_actions_version: ${{ env.tf_actions_version }}